version: '3'

services:
  quantum_container1:
    volumes:
      - ./quantum_container1:/app
    networks:
      - quantum_network
    build:
      context: quantum_container1
      dockerfile: Dockerfile
    command: 
    - bash
    - -c
    - |
      . venv/bin/activate
      python3 /app/quantum_server.py

  quantum_container2:
    volumes:
      - ./quantum_container2:/app
    networks:
      - quantum_network
    build:
      context: quantum_container2
      dockerfile: Dockerfile
    command: 
    - bash
    - -c
    - |
      . venv/bin/activate
      python3 /app/quantum_client.py

  machine_a:
    build: ./machine_a
    volumes:
      - ./machine_a:/app
    networks:
      - quantum_network

  machine_b:
    build: ./machine_b
    volumes:
      - ./machine_b:/app
    networks:
      - quantum_network

networks:
  quantum_network:
    driver: bridge